//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public string notOgrenciNo { get; set; }
        public string notDersKodu { get; set; }
        public string notVize { get; set; }
        public string notFinal { get; set; }
        public string notOrtalama { get; set; }
        public int notUyeId { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
