//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public string ogrNo { get; set; }
        public string ogrTC { get; set; }
        public string ogrAd { get; set; }
        public string ogrSoyad { get; set; }
        public string ogrCinsiyet { get; set; }
        public string ogrTelefon { get; set; }
        public string ogrMail { get; set; }
        public string ogrBolumKodu { get; set; }
        public int ogrUyeId { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Notlar Notlar { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
